export interface IUserinfo{
    RESP_CODE: string,
    RESP_MSG: string,
    RESP_TIME: string,
    TransactionID?: string,
    InsurerCode?: string,
    RefID?: string,
    VerifiedMTL?: string,
    Bu?: string,
    Lang?: string,
    ConsentRefCode?: string,
    ConsentCode?: string,
    HospitalCode?: string,
    HospitalName?: string,
    ClaimCause?: string,
    ServiceTypeCode?: string,
    HN?: string,
    ANOrVN?: string,
    FirstName?: string,
    LastName?: string,
    Phone?: string,
    DateOfBirth?: string,
    PasscodePin?: string,
    DoctorRecommendation?: string,
    IPDorOPD?: string,
    IncidentDate?: string,
    IncidentTime?: string,
    TreatmentDate?: string,
    TreatmentTime?: string,
    IsFollowUp?: string,
    CauseFormMotorcycle?: string,
    FirstDateForThisillness?:  string,
    ChiefComplaint?: string,
    OpinionSymptomForThisillness?: string,
    SearchOption?: string,
    CID_PASSPORT?: string,
    ID?: string,
    PolicyNumber?: string,
    PriviledgeCardNo?: string,
    UnderlyingDiseasesCode?: string,
    UnderlyingDiseasesDescription?: string,
    PrincipleDiagnosisCode?: string,
    PrincipleDiagnosisDescription?: string,
    SecondDiagnosisCode?: string,
    SecondDiagnosisDescription?: string,
    ComorbidityCode?: string,
    ComorbidityDescription?: string,
    ComplicationCode?: string,
    ComplicationDescription?: string,
    OtherCodeICD10?: string,
    OtherCodeICD10Description?: string,
    TreatmentDescription?: string,
    SurgeryCode1?: string,
    SurgeryDescription1?: string,
    MedicalLicenseNo?: string,
    DoctorName?: string,
    ProductType?: string,
    TotalAmount?: string,
    Totaldiscount?: string,
    BillAmount?: string,
    SIMBType?: string,
    User_name?: string,
    Medical_info_ID?: string,
    PaidAmount?: number,
    PaymentChannel?: string,
    PaymentStage?: string,
    CouponCode?: string,
    CouponDiscount?: number,
    ClaimDiscount?: number,
    HospitalRemark?: string,
    Title?: string,
    Nationality?: string
    Email?: string,
    ConsentProduct?: string,
    ConsentCampaign?: string,
    ClientNo?: string,
    Indication?: string,
    CauseOfaccidentICD10Code?: string,
    CauseOfaccidentICD10Description?: string,
    AlcoholOrDrugYesOrNo?: string,
    AlcoholOrDrugDescription?: string,
    PatientClinicalFindings?: string,
    SurgeryCode2?: string,
    SurgeryDescription2?: string,
    SurgeryCode3?: string,
    SurgeryDescription3?: string,
    RelatedToAlcoholYesOrNo?: string,
    RelatedToAddictionYesOrNo?: string,
    PatientPregnantYesOrNo?: string,
    RelatedToInfertilityYesOrNo?: string,
    MedicalHistoryDiagnosis?: string,
    MedicalHistoryTreatment?: string,
    MedicalHistoryPhysicianAndHospName?: string,
    ElectronicSignature?: string,
    Remark?: string
}
export class PaymentInfo implements IUserinfo{

    RESP_CODE: string;
    RESP_MSG: string;
    RESP_TIME: string;
    TransactionID?: string;
    InsurerCode?: string;
    RefID?: string;
    VerifiedMTL?: string;
    Bu?: string;
    Lang?: string;
    ConsentRefCode?: string;
    ConsentCode?: string;
    HospitalCode?: string;
    HospitalName?: string;
    ClaimCause?: string;
    ServiceTypeCode?: string;
    HN?: string;
    ANOrVN?: string;
    FirstName?: string;
    LastName?: string;
    Phone?: string;
    DateOfBirth?: string;
    PasscodePin?: string;
    DoctorRecommendation?: string;
    IPDorOPD?: string;
    IncidentDate?: string;
    IncidentTime?: string;
    TreatmentDate?: string;
    TreatmentTime?: string;
    IsFollowUp?: string;
    CauseFormMotorcycle?: string;
    FirstDateForThisillness?:  string;
    ChiefComplaint?: string;
    OpinionSymptomForThisillness?: string;
    SearchOption?: string;
    CID_PASSPORT?: string;
    ID?: string;
    PolicyNumber?: string;
    PriviledgeCardNo?: string;
    UnderlyingDiseasesCode?: string;
    UnderlyingDiseasesDescription?: string;
    PrincipleDiagnosisCode?: string;
    PrincipleDiagnosisDescription?: string;
    SecondDiagnosisCode?: string;
    SecondDiagnosisDescription?: string;
    ComorbidityCode?: string;
    ComorbidityDescription?: string;
    ComplicationCode?: string;
    ComplicationDescription?: string;
    OtherCodeICD10?: string;
    OtherCodeICD10Description?: string;
    TreatmentDescription?: string;
    SurgeryCode1?: string;
    SurgeryDescription1?: string;
    MedicalLicenseNo?: string;
    DoctorName?: string;
    ProductType?: string;
    TotalAmount?: string;
    Totaldiscount?: string;
    BillAmount?: string;
    SIMBType?: string;
    User_name?: string;
    Medical_info_ID?: string;
    PaidAmount?: number;
    PaymentChannel?: string;
    PaymentStage?: string;
    CouponCode?: string;
    CouponDiscount?: number;
    ClaimDiscount?: number;
    HospitalRemark?: string;
    Title?: string;
    Nationality?: string;
    Email?: string;
    ConsentProduct?: string;
    ConsentCampaign?: string;
    ClientNo?: string;
    Indication?: string;
    CauseOfaccidentICD10Code?: string;
    CauseOfaccidentICD10Description?: string;
    AlcoholOrDrugYesOrNo?: string;
    AlcoholOrDrugDescription?: string;
    PatientClinicalFindings?: string;
    SurgeryCode2?: string;
    SurgeryDescription2?: string;
    SurgeryCode3?: string;
    SurgeryDescription3?: string;
    RelatedToAlcoholYesOrNo?: string;
    RelatedToAddictionYesOrNo?: string;
    PatientPregnantYesOrNo?: string;
    RelatedToInfertilityYesOrNo?: string;
    MedicalHistoryDiagnosis?: string;
    MedicalHistoryTreatment?: string;
    MedicalHistoryPhysicianAndHospName?: string;
    ElectronicSignature?: string;
    Remark?: string;
    
    
    constructor() {
        
    }

   

}
